/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SaranRouteImport } from './routes/saran'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as KamusRouteImport } from './routes/kamus'
import { Route as CariRouteImport } from './routes/cari'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as KataSlugRouteImport } from './routes/kata.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SaranRoute = SaranRouteImport.update({
  id: '/saran',
  path: '/saran',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const KamusRoute = KamusRouteImport.update({
  id: '/kamus',
  path: '/kamus',
  getParentRoute: () => rootRouteImport,
} as any)
const CariRoute = CariRouteImport.update({
  id: '/cari',
  path: '/cari',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const KataSlugRoute = KataSlugRouteImport.update({
  id: '/kata/$slug',
  path: '/kata/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cari': typeof CariRoute
  '/kamus': typeof KamusRoute
  '/kontak': typeof KontakRoute
  '/saran': typeof SaranRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/tentang': typeof TentangRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/kata/$slug': typeof KataSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cari': typeof CariRoute
  '/kamus': typeof KamusRoute
  '/kontak': typeof KontakRoute
  '/saran': typeof SaranRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/tentang': typeof TentangRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/kata/$slug': typeof KataSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cari': typeof CariRoute
  '/kamus': typeof KamusRoute
  '/kontak': typeof KontakRoute
  '/saran': typeof SaranRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/tentang': typeof TentangRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/kata/$slug': typeof KataSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cari'
    | '/kamus'
    | '/kontak'
    | '/saran'
    | '/sitemap.xml'
    | '/support'
    | '/tentang'
    | '/blog/$slug'
    | '/kata/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cari'
    | '/kamus'
    | '/kontak'
    | '/saran'
    | '/sitemap.xml'
    | '/support'
    | '/tentang'
    | '/blog/$slug'
    | '/kata/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/cari'
    | '/kamus'
    | '/kontak'
    | '/saran'
    | '/sitemap.xml'
    | '/support'
    | '/tentang'
    | '/blog/$slug'
    | '/kata/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CariRoute: typeof CariRoute
  KamusRoute: typeof KamusRoute
  KontakRoute: typeof KontakRoute
  SaranRoute: typeof SaranRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  TentangRoute: typeof TentangRoute
  BlogSlugRoute: typeof BlogSlugRoute
  KataSlugRoute: typeof KataSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saran': {
      id: '/saran'
      path: '/saran'
      fullPath: '/saran'
      preLoaderRoute: typeof SaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kamus': {
      id: '/kamus'
      path: '/kamus'
      fullPath: '/kamus'
      preLoaderRoute: typeof KamusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cari': {
      id: '/cari'
      path: '/cari'
      fullPath: '/cari'
      preLoaderRoute: typeof CariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kata/$slug': {
      id: '/kata/$slug'
      path: '/kata/$slug'
      fullPath: '/kata/$slug'
      preLoaderRoute: typeof KataSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CariRoute: CariRoute,
  KamusRoute: KamusRoute,
  KontakRoute: KontakRoute,
  SaranRoute: SaranRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  TentangRoute: TentangRoute,
  BlogSlugRoute: BlogSlugRoute,
  KataSlugRoute: KataSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
